quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update
quarkus.http.host=0.0.0.0
mp.jwt.verify.issuer=http://localhost:8080/realms/internship-management
mp.jwt.verify.publickey.location=http://keycloak:8080/realms/internship-management/protocol/openid-connect/certs
user-service.url=http://user-service:8080