quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update
quarkus.http.host=0.0.0.0

mp.jwt.verify.issuer=http://localhost:8080/realms/internship-management
mp.jwt.verify.publickey.location=http://keycloak:8080/realms/internship-management/protocol/openid-connect/certs

quarkus.rest-client.user-service.url=http://user-service:8080
quarkus.rest-client.internship-service.url=http://internship-service:8080

smallrye.jwt.path.groups=/realm_access/roles